//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timee.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHints {
            get {
                return ((bool)(this["ShowHints"]));
            }
            set {
                this["ShowHints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainTasks {
            get {
                return ((string)(this["MainTasks"]));
            }
            set {
                this["MainTasks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<Root></Root>")]
        public string PredefinedTasks {
            get {
                return ((string)(this["PredefinedTasks"]));
            }
            set {
                this["PredefinedTasks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotKeys {
            get {
                return ((string)(this["HotKeys"]));
            }
            set {
                this["HotKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<UserConfiguration>
        <Location>
          <Location Order=""1"" Name=""LGBS Gliwice"">1</Location>
        </Location>
        <Project>
          <Project Order=""1"" Name=""LGBS | Timesheet"">465</Project>
        </Project>
        <Sub-project>
          <Sub-project Order=""1"" Name=""Timee"" Parent=""LGBS | Timesheet"" ParentId=""465"">12655</Sub-project>
        </Sub-project>
        <Task>
          <Task Order=""1"" Name=""Development"" Parent=""Timee"" ParentId=""12655"">10291</Task>
          <Task Order=""2"" Name=""Research"" Parent=""Timee"" ParentId=""12655"">15832</Task>
          <Task Order=""3"" Name=""Testing"" Parent=""Timee"" ParentId=""12655"">20740</Task>
          <Task Order=""4"" Name=""Wsparcie dla praktykanta"" Parent=""Timee"" ParentId=""12655"">56062</Task>
        </Task>
</UserConfiguration>")]
        public string UserConfiguration {
            get {
                return ((string)(this["UserConfiguration"]));
            }
            set {
                this["UserConfiguration"] = value;
            }
        }
    }
}
